### ISSUE TITLE
Configurar máquina vagrant

### ISSUE THREAD

**Issue by joserobleda** [thewildboard/wildboard#1]
La idea es poder iniciar una instancia de wildboard lo más rápido posible, así que vamos a montar un Vagrant con ansible.

**Comment by albertoprad** [comment]
Ya esta subida la rama con el provision de ansible para vagrant. Para levantar una instancia es necesario tener instalado virtualbox y vagrant.

Desde la raiz del repo ejecutamos `vagrant up`, una vez instalada accedemos a ella con `vagrant ssh`
