### ISSUE TITLE
Mover clave secreta de sesión al archivo de configuración

### ISSUE THREAD

**Issue by joserobleda** [thewildboard/wildboard#18]
Creo que el "secret" que aparece en el siguiente código de `server.js`:

``` js

sessions({
    // cookie name dictates the key name added to the request object
    cookieName: 'session',
    // should be a large unguessable string
    secret: 'mynameisralphwiggum',
    // how long the session will stay valid in ms
    duration: 259200 * 1000
})
```

Debería estar en el archivo de configuración y ser un random que se genere junto con el archivo.

**Comment by muit** [comment]
cierto, se me paso porque lo hice al principio

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
Sobre 22/07/2015 18:22:56, Jose Ignacio notifications@github.com escribió:
Creo que el "secret" que aparece en el siguiente código de server.js:
sessions({ // cookie name dictates the key name added to the request object cookieName: 'session', // should be a large unguessable string secret: 'mynameisralphwiggum', // how long the session will stay valid in ms duration: 259200 \* 1000 })
Debería estar en el archivo de configuración y ser un random que se genere junto con el archivo.
