### ISSUE TITLE
Ejemplos de respuesta de la API de backend

### ISSUE THREAD

**Issue by joserobleda** [thewildboard/wildboard#2]
Como hablamos ayer, la idea es que @muit nos cree un par de ejemplos para las rutas:

`/widgets`
`/widget/:widget`

Para que @lisssb y @guardabrazo puedan avanzar en renderizar los widgets en pantalla.

Creo que podemos ir creando ejemplos de cada ruta en:

`/docs/api/widgets.md`
`/docs/api/widget/_widget.md`

O algo así, de forma que esa carpeta refleje en cierta medida la API, así se puede ver aún más claro el esquema.

**Comment by muit** [comment]
Docs on boards api:

Add request and return json example to:
- [x] GET api/boards
- [x] POST api/boards
- [x] GET api/boards/:id
- [x] GET api/boards/:id/widgets
- [x] POST api/boards/:id/widgets
- [x] GET api/widgets/:id

**Comment by joserobleda** [comment]
@lisssb @guardabrazo parece que @muit ya nos ha puesto los ejemplos, podéis echarle un vistazo a ver si los entendéis bien?
