### ISSUE TITLE
3. Acceso directo a login

### ISSUE THREAD

**Issue by joserobleda** [thewildboard/wildboard#48]
La idea es que estando en una app, podamos poner un enlace directo al proceso de autorización. Por ejemplo:
1. estamos en la página principal de dokify
2. el usuario hace clic sobre el enlace que pon "wildboard"
3. se redirige al usuario a wildboard, pero de forma inmediata, sin pantallas intermedias, se pide autorización
4. el usuario acepta la autorización
5. el usuario vuelve a estar en widlboard, pero ya logueado con el el provider dokify

@muit @lisssb se entiende esto? No se bien a quien asignar esto, me decís vosotros, vale?

**Comment by muit** [comment]
Si pero creo que tendría mas peso por ahora poder crear un nuevo proveedor de login desde la config

PD: English is better here

**Comment by joserobleda** [comment]
> Si pero creo que tendría mas peso por ahora... 

La issue en sí no determina prioridad, para eso están las milestones. La he puesto en la _0.3_. 

> ...poder crear un nuevo proveedor de login desde la config

No se a que te refieres, pero si hay que hacer cosas, tan pronto como las sepas pon una issue, para que no se nos pase nada.

> PD: English is better here

@muit bien. Pero aún nos cuesta entendernos en castellano, vamos paso a paso.
