### ISSUE TITLE
2. Implement dinamic logins (oauth2)

### ISSUE THREAD

**Issue by muit** [thewildboard/wildboard#49]
Create different logins from config.js

**Comment by joserobleda** [comment]
What does this means exactly? I mean, what is a "login" in our context?

**Comment by muit** [comment]
For example: logging in  to wildboard with dokify, (to be able to create boards, etc)

**Comment by joserobleda** [comment]
Ok. Then we should update the description of this issue to something more precise. What we want to do here is to implement the oauth flow based on the configuration file, right?
