### ISSUE TITLE
Move to express

### ISSUE THREAD

**Issue by muit** [thewildboard/wildboard#5]
Move the server structure to express

**Comment by joserobleda** [comment]
BRAVO!

![](http://tclhost.com/3Aahvph.gif)

**Comment by muit** [comment]
ya esta echo -__-

**Comment by joserobleda** [comment]
A, pues ponle el "fixes" en el pull request para que se cierre esta issue cuando se haga el merge.
(si no sabes lo que es, aquí se explica: https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by muit** [comment]
Ahora despues lo cierro, cuando lo tenga bien testeado

**Comment by muit** [comment]
Los test de travis fallan por alguna configuración, no hay errores por ahora
